### ISSUE TITLE
Border Alignment Issue

### ISSUE THREAD

**Issue by natahn** [soukoku/ModernWPF#11]
Hello. Great UI and SDK thankyou. Works great. One small issue i've found is that the border doesn't correctly square off on the edges as it's missing a couple of pixels in length.

[Screenshot of Issue](http://m48i.imgup.net/BorderIssufdd9.png)

I have managed to fix this by editting, ModernWPF/Control/BorderWindow -> UpdatePosn with the following code bu tadjusting the pad size and the Top/Left position.

`

```
        this.Left = left;
        this.Top = top;
        this.Width = width;
        this.Height = height;
        var pad = ( 2 * PadSize ) - 2 ;  // adjusted
        switch (Side)
        {
            case BorderSide.Left:
            case BorderSide.Right:
                this.Top -= 1; // new
                BorderLength = Math.Max(0, height - pad );
                break;
            case BorderSide.Top:
            case BorderSide.Bottom:
                this.Left -= 1; // new
                BorderLength = Math.Max( 0, width - pad );
                break;
        }
```

`
[Screenshot Fixed](http://n62i.imgup.net/BorderFixe215e.png)

It would be great to have this in the official branch though. Thanks again for the great library. Certainly saved me some time!

**Comment by soukoku** [comment]
Thanks, will incorporate in next update. I still need to play with different DPI for more tests.

**Comment by soukoku** [comment]
Should be fixed now.
