### ISSUE TITLE
Look into adding per-monitor dpi support

### ISSUE THREAD

**Issue by soukoku** [soukoku/ModernWPF#7]
Moving a window between monitors of different DPI makes it blurry in all but the monitors with the DPI user logged in with first. See if adding per-monitor aware DPI support can fix that.

**Comment by soukoku** [comment]
Close enough opt-in ability in sample.

**Comment by MagicAndre1981** [comment]
target the solution for 4.6.2 and you'll get per monitor DPI awareness by default:

https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/#wpf

**Comment by soukoku** [comment]
I'm not lucky enough to have all users on the latest and greatest. Since this is a lib it should be up to the app developer to decide which one to use, and mine is opt-in just like the framework's implementation.
